/*
 * Phonebook API
 * RESTful API for Messente phonebook
 *
 * OpenAPI spec version: 0.0.4
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.messente.phonebook;

import com.messente.ApiException;
import com.messente.phonebook.ErrorResponse;
import com.messente.phonebook.GroupEnvelope;
import com.messente.phonebook.GroupListEnvelope;
import com.messente.phonebook.GroupName;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupsApi
 */
@Ignore
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    
    /**
     * 
     *
     * Creates a new group with the provided name.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGroupTest() throws ApiException {
        GroupName groupName = null;
        GroupEnvelope response = api.createGroup(groupName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Deletes a group.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGroupTest() throws ApiException {
        String groupId = null;
        api.deleteGroup(groupId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Lists a group.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchGroupTest() throws ApiException {
        String groupId = null;
        GroupEnvelope response = api.fetchGroup(groupId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns all groups.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchGroupsTest() throws ApiException {
        GroupListEnvelope response = api.fetchGroups();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Updates a group with the provided name.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGroupTest() throws ApiException {
        String groupId = null;
        GroupName groupName = null;
        GroupEnvelope response = api.updateGroup(groupId, groupName);

        // TODO: test validations
    }
    
}
